
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version') %}

package:
  name: access-nri-intake
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/a/access-nri-intake/access_nri_intake-{{ version }}.tar.gz"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - python
    - pip
    - versioneer
  run:
    - dask
    - h5netcdf
    - hpcpy
    - metpy
    - pint
    - python>=3.10
    - xarray

about:
  home: https://github.com/ACCESS-NRI/metplan
  license: Apache Software License 2.0
  summary: Python package for preprocessing the met forcings for land models.
  doc_url: https://access-nri-intake-catalog.readthedocs.io/en/latest/

extra:
  recipe-maintainers: