name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3.3.0
        with:
            miniconda-version: "latest"
            python-version: ${{ matrix.python-version }}
            environment-file: ci/environment-${{ matrix.python-version }}.yml
            activate-environment: metplan-${{ matrix.python-version }}
            auto-activate-base: false

      - name: Install source
        shell: bash -l {0}
        run: python -m pip install .

      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      - name: Run tests
        shell: bash -l {0}
        run: coverage run -m --source=metplan pytest tests
      
      - name: Generate coverage report
        shell: bash -l {0}
        run: coverage xml

      - name: Upload code coverage
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe
        with:
          token:  ${{ secrets.codecov_token }} 
          files: ./coverage.xml
